


title: Vše o mandalách
baseURL: https://vigilant-pasteur-e39f85.netlify.com/
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: <p>Kristýna Světnicová: {{ Params.author }}</p>

